---
title: Maffe ogen
hero_image: images/banner.png
description: Maak je eigen app met een personage wiens ogen de muisaanwijzer volgen
version: 4
listed: true
copyedit: false
last_tested: '2021-02-25'
steps:
  - title: Je gaat maken
  - title: Creëer je personage
  - title: Maak maffe ogen
    completion:
      - engaged
  - title: Sprite-effecten toevoegen
    completion:
      - internal
  - title: Snelle quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Verbeter je project
  - title: Deel en speel