---
title: Alberne Augen
hero_image: images/banner.png
description: Erstelle deine eigene App mit einem Charakter, dessen Augen dem Mauszeiger folgen
meta_title: Scratch Coding Projekte für Kinder und Jugendliche | Alberne Augen
meta_description: Lerne Coding in Scratch mit den Coding Projekten der Raspberry Pi Foundation für Kinder und Jugendliche. Erstelle mit Scratch eine Animation und einen Charakter mit albernen Augen.
version: 4
listed: true
copyedit: false
last_tested: '2021-02-25'
steps:
  - title: Das wirst du machen
  - title: Erstelle deinen Charakter
  - title: Mache alberne Augen
    completion:
      - engaged
  - title: Figureneffekte hinzufügen
    completion:
      - internal
  - title: Kurzes Quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Verbessere Dein Projekt
  - title: Teile und spiele
  - title: Wie geht es weiter?
