---
title: Olhos engraçados
hero_image: images/banner.png
description: Crie seu próprio aplicativo com um personagem cujos olhos seguem o ponteiro do mouse
meta_title: Scratch coding projects for kids and teens | Silly eyes
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch animation and create a character with silly eyes.
version: 4
listed: true
copyedit: false
last_tested: '2021-02-25'
steps:
  - 
    title: You will make
  - 
    title: Create your character
  - 
    title: Faça olhos engraçados
    completion:
      - engaged
  - 
    title: Add sprite effects
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Upgrade your project
  - 
    title: Share and play
  - 
    title: What next?
