---
title: Ojos tontos
hero_image: images/banner.png
description: Crea tu propia aplicación con un personaje cuyos ojos siguen el puntero
  del ratón
version: 4
listed: true
copyedit: false
last_tested: '2021-02-25'
steps:
- title: Lo que harás
- title: Crea tu propio personaje
- title: Haz ojos tontos
  completion:
  - engaged
- title: Añade efectos al objeto
  completion:
  - internal
- title: Examen rápido
  knowledge_quiz:
    path: quiz1
    version: 1
    questions: 3
    passing_score: 3
  completion:
  - external
- title: Mejora tu proyecto
- title: Comparte y juega
- title: '¿Qué sigue?'
