---
title: Roliga ögon
hero_image: images/banner.png
description: Skapa din egen app med en karaktär vars ögon följer muspekaren
version: 4
listed: true
copyedit: false
last_tested: '2021-02-25'
steps:
  - title: Du kommer att skapa
  - title: Skapa din karaktär
  - title: Gör roliga ögon
    completion:
      - engaged
  - title: Lägg till sprajteffekter
    completion:
      - internal
  - title: Snabbt quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Uppgradera ditt projekt
  - title: Dela och spela