---
title: Yeux rigolos
hero_image: images/banner.png
description: Créer ta propre application avec un personnage dont les yeux suivent le pointeur de la souris
version: 4
listed: true
copyedit: false
last_tested: '2021-02-25'
steps:
  - title: Ce que tu vas faire
  - title: Créer ton personnage
  - title: Créer des yeux rigolos
    completion:
      - engaged
  - title: Ajouter des effets de sprite
    completion:
      - internal
  - title: Questionnaire rapide
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Améliorer ton projet
  - title: Partager et jouer